[package]
name = "state"
version = "0.1.0"
edition = "2021"

[dependencies]
parsing = { path = "../parsing" }
shared = { path = "../shared" }
itertools="*"
criterion = "0.5.1"
bitvec = "1.0.1"

[[bench]]
name = "init"
harness = false
